### ISSUE TITLE
Firefox authorization problem

### ISSUE THREAD

**Issue by SheepaCZE** [danniehansen/activity-timer#40]
Hi, just for the record, I am gonna post here what we talked about through the email.

I probably found a bug that only occurs in the Firefox browser. I've tried downgrading, updating, reinstalling, clearing memory, nothing helped. Once I use any browser based on chrome core, for example Brave, everything is perfectly fine. I am talking about the "Activity timer history" entry, if is opened in Firefox, most likely ends with a big white nothing. The picture below. I also tried it on my laptop with Firefox browser, with the same result. I hope this problem will be easy to replicate.

Thank you for possibly solving the problem.

![obrazek](https://user-images.githubusercontent.com/38692682/120908766-356d7480-c66e-11eb-86e2-37dfd61ee553.png)

**Comment by danniehansen** [comment]
Thank you for reporting this @SheepaCZE - I will look into this, this weekend. Will keep you posted.

**Comment by danniehansen** [comment]
@SheepaCZE Not 100% sure it's the same issue as you've described here. But the only thing i was able to find was when clicking 'Authorize' then nothing happened. Should be fixed in latest release - can you give it a shot? (remember to clear your browser cache)

**Comment by SheepaCZE** [comment]
Hello.

I'm afraid my problem still persists. I have cleaned the entire system, both the main PC and the laptop. The same problem on both devices. I am also attaching samples to be sure that everything has been cleaned properly. I log back into Trello, click on "activity timer history" and can't do anything. :(

![c1](https://user-images.githubusercontent.com/38692682/121775777-ec478400-cb89-11eb-8454-e9cc72cc06a0.png)
![c2](https://user-images.githubusercontent.com/38692682/121775787-f5385580-cb89-11eb-9a0f-79aa0c21fad4.png)
![c1](https://user-images.githubusercontent.com/38692682/121775796-fec1bd80-cb89-11eb-8ed4-ea407e83e8c4.png)

**Comment by SheepaCZE** [comment]
The main problem is that I can't even get to the authorization, I have a white window from the very beginning.

**Comment by danniehansen** [comment]
@SheepaCZE Ouch - that's unfortunate. I think what would help me further investigate this is the devtools console output. I've tested on 2 separate systems with a fresh Firefox install & there it's working as expected.

To supply devtools console output you can right click anywhere on your trello board & choose 'Inspect'. Once the inspector is open - navigate to "Console" & reload the page. Afterwards you should be able to click on the 'Activity timer history' that opens the overlay. Once overlay is shown - copy everything from the console into this issue. Hopefully a useful exception is thrown in the developer console & will help me track down the issue.

**Comment by SheepaCZE** [comment]
So I played with it some more and I think I found the hidden problem. Both of my browsers had "Strict" Browser privacy set by default for some reason, which for some reason this item doesn't like and therefore shows a white window. When I switched the browser to "Standard" mode, everything worked again. Apologies for the mystification. Interesting that I had the default strict settings for both.
![ffstrict](https://user-images.githubusercontent.com/38692682/121776470-5877b700-cb8d-11eb-819e-fcc3720ae85d.png)
![ffstandard](https://user-images.githubusercontent.com/38692682/121776472-5ada1100-cb8d-11eb-8311-35ed0a652cc6.png)

**Comment by danniehansen** [comment]
@SheepaCZE Ah - that explains it. No need for apologies - while i cannot do anything about this in particular because the browser is blocking the Trello power-up at a higher level it did lead me on to find an issue in Firefox with the 'Authorize' button. I'll mark the issue as closed for now :) Let me know if you experience anything else unusual.
